### ISSUE TITLE
Can't install on Ubuntu (Docker)

### ISSUE THREAD

**Issue by rubendibattista** [bmcage/odes#57]
Using `ubuntu:16.04` image. 

`apt-get install python python-dev python-virtualenv virtualenvwrapper cmake cmake-curses-gui libopenblas-* libatlas-* liblapack-*`

I compiled sundials with LAPACK interface as for documentation

`mkvirtualenv pysundials`
`pip install numpy`
`pip install scikits.odes`

```
tid@ab44bef2e9ee:~$ SUNDIALS_INST=/opt/sundials pip install scikits.odes
Collecting scikits.odes
  Using cached scikits.odes-2.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    =============================================
    parent package is scikits
    top path is /tmp/pip-build-qar7lr/scikits.odes
    =============================================
    pkgconfig module not found, using preset paths
    SUNDIALS installation path set to `/opt/sundials` via $SUNDIALS_INST.
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/home/tid/.virtualenvs/pysundials/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
    customize UnixCCompiler
    C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC

    creating /tmp/tmpYg2j4J/tmp
    creating /tmp/tmpYg2j4J/tmp/tmpYg2j4J
    compile options: '-c'
    x86_64-linux-gnu-gcc: /tmp/tmpYg2j4J/source.c
    /tmp/tmpYg2j4J/source.c:1:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
     void zungqr();
     ^
    /tmp/tmpYg2j4J/source.c: In function 'main':
    /tmp/tmpYg2j4J/source.c:4:13: warning: implicit declaration of function 'zungqr_' [-Wimplicit-function-declaration]
                 zungqr_();
                 ^
    x86_64-linux-gnu-gcc -pthread /tmp/tmpYg2j4J/tmp/tmpYg2j4J/source.o -lopenblas -o /tmp/tmpYg2j4J/a.out
    customize UnixCCompiler
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/lib']
        language = c
        define_macros = [('HAVE_CBLAS', None)]

      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/lib']
        language = c
        define_macros = [('HAVE_CBLAS', None)]

    Found LAPACK paths via lapack_opt ...
    =============================================
    parent package is scikits.odes
    top path is /tmp/pip-build-qar7lr/scikits.odes
    =============================================
    cython -2 -o /tmp/pip-build-qar7lr/scikits.odes/scikits/odes/sundials/common_defs.c.new /tmp/pip-build-qar7lr/scikits.odes/scikits/odes/sundials/common_defs.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qar7lr/scikits.odes/setup.py", line 62, in <module>
        setup_package()
      File "/tmp/pip-build-qar7lr/scikits.odes/setup.py", line 56, in setup_package
        '': ['*.pxd'],
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-qar7lr/scikits.odes/setup.py", line 36, in configuration
        config.add_subpackage(DISTNAME)
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scikits/odes/setup.py", line 26, in configuration
        config.add_subpackage('sundials')
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "/home/tid/.virtualenvs/pysundials/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scikits/odes/sundials/setup.py", line 114, in configuration
        include_dirs=[])
      File "/tmp/pip-build-qar7lr/scikits.odes/scikits/odes/_build.py", line 85, in cython
        status = subprocess.call(['cython', '-2', '-o', c_file_new, pyxfile])
      File "/usr/lib/python2.7/subprocess.py", line 523, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qar7lr/scikits.odes/
(pysundials) tid@ab44bef2e9ee:~$ ls /opt/sundials/
LICENSE  examples  include  lib
```

What am I missing?

**Comment by rubendibattista** [comment]
Missing Cython. Too bad.
