### ISSUE TITLE
scikits.odes installed successfully through pip3 / git version but failed at od.test()

### ISSUE THREAD

**Issue by sakimilo** [bmcage/odes#71]
Hi, 

What I did: 
```
sudo apt update
sudo apt upgrade
sudo apt install build-essential python3-gdbm cmake
sudo apt install python3-dev gfortran libblas-dev libopenblas-dev liblapack-dev libatlas-base-dev

curl -o sundials-2.7.0.tar.gz https://computation.llnl.gov/projects/sundials/download/sundials-2.7.0.tar.gz
tar -xzf sundials-2.7.0.tar.gz
mkdir build-sundials-2.7.0
cd build-sundials-2.7.0/
cmake -DLAPACK_ENABLE=ON -DCMAKE_INSTALL_PREFIX=/usr/lib/sundials-2.7.0/ /home/ubuntu/sundials-2.7.0

After running above, Return: 
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- The Fortran compiler identification is GNU 5.4.0
-- Searching for a Fortran compiler... /usr/bin/gfortran
-- Trying to compile and link a simple Fortran program... OK
-- Determining Fortran name-mangling scheme... OK
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Looking for LAPACK libraries... OK
-- Checking if Lapack works... OK
-- Added NVECTOR_SERIAL module
-- Added ARKODE module
-- Added CVODE module
-- Added CVODES module
-- Added IDA module
-- Added IDAS module
-- Added KINSOL module
-- Found PythonInterp: /usr/bin/python (found version "2.7.12")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/build-sundials-2.7.0
```

(And I have changed python to python3.6 in CMakeCache.txt as below:
```
//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6
//Details about finding PythonInterp
FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp:INTERNAL=[/usr/bin/python3.6][]
```
And rerun ```cmake -DLAPACK_ENABLE=ON -DCMAKE_INSTALL_PREFIX=/usr/lib/sundials-2.7.0/ /home/ubuntu/sundials-2.7.0;```

Result:
```
-- The Fortran compiler identification is GNU 5.4.0
-- Searching for a Fortran compiler... /usr/bin/gfortran
-- Trying to compile and link a simple Fortran program... OK
-- Determining Fortran name-mangling scheme... OK
-- Looking for LAPACK libraries... OK
-- Checking if Lapack works... OK
-- Added NVECTOR_SERIAL module
-- Added ARKODE module
-- Added CVODE module
-- Added CVODES module
-- Added IDA module
-- Added IDAS module
-- Added KINSOL module
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.4")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/build-sundials-2.7.0
)

sudo make install;
```
Result of installation seems no problem at all.

I have changed .bashrc $SUNDIALS_INST as 
```export SUNDIALS_INST=/usr/lib/sundials-2.7.0/```

# install scikits.odes through pip3 (I have installed Cython through pip3 as well)

```sudo pip3 install scikits.odes;```

Result:
```
Collecting scikits.odes
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from scikits.odes)
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python3.6/dist-packages (from scipy->scikits.odes)
Installing collected packages: scikits.odes
Successfully installed scikits.odes-2.3.2
```

However, when i try to run test code as below:

ubuntu:~/ctrnn_ann$ ipython
```
Python 3.6.4 (default, Jan 28 2018, 17:52:01)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import scikits.odes as od;

In [2]: od.test()
Running unit tests for scikits.odes
NumPy version 1.13.3
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python3.6/dist-packages/numpy
Python version 3.6.4 (default, Jan 28 2018, 17:52:01) [GCC 5.4.0 20160609]
nose version 1.3.7
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
libsundials_ida.so.2: cannot open shared object file: No such file or directory
libsundials_cvode.so.2: cannot open shared object file: No such file or directory
EEException ignored in: <bound method dae.__del__ of <scikits.odes.dae.dae object at 0x7fca5fbb3be0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/dae.py", line 445, in __del__
    del self._integrator
AttributeError: _integrator
EException ignored in: <bound method dae.__del__ of <scikits.odes.dae.dae object at 0x7fca5fbb3e10>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/dae.py", line 445, in __del__
    del self._integrator
AttributeError: _integrator
E.EEEEEE.EE.EEEE
======================================================================
ERROR: Check the ddaspk solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 52, in test_ddaspk
    problem = problem_cls()
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 211, in __init__
    old_api=False,
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: Check the ida solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 71, in test_ida
    self._do_problem(problem, 'ida', old_api=False, **problem.ida_pars)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 27, in _do_problem
    ig = dae(integrator, res, jacfn=jac, old_api=old_api)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/dae.py", line 280, in __init__
    integrator = find_dae_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/dae.py", line 481, in find_dae_integrator
    raise ValueError('Integrator name %s does not exsist' % name)
ValueError: Integrator name ida does not exsist

======================================================================
ERROR: Check the ida solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 65, in test_ida_old_api
    self._do_problem(problem, 'ida', old_api=True, **problem.ida_pars)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 27, in _do_problem
    ig = dae(integrator, res, jacfn=jac, old_api=old_api)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/dae.py", line 280, in __init__
    integrator = find_dae_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/dae.py", line 481, in find_dae_integrator
    raise ValueError('Integrator name %s does not exsist' % name)
ValueError: Integrator name ida does not exsist

======================================================================
ERROR: Check the lsodi solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 58, in test_lsodi
    problem = problem_cls()
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_dae.py", line 211, in __init__
    old_api=False,
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_get_info_is_exposed_on_ode (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_get_info_returns_dict (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_ode_exposes_num_rhs_evals (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_we_integrated_correctly (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_ode_exposes_num_njtimes_evals (scikits.odes.tests.test_get_info.GetInfoTestSpils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_get_info.py", line 50, in setUp
    self.ode = ode('cvode', rhs, linsolver="spgmr", old_api=False)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_odeint (scikits.odes.tests.test_odeint.TestOdeint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_odeint.py", line 47, in test_odeint
    self._do_problem(problem)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_odeint.py", line 33, in _do_problem
    sol = odeint(problem.f, t, problem.z0, method=method)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/odeint.py", line 215, in odeint
    solver = ode(int_name, rhsfun, **options)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: scikits.odes.tests.test_odeint.test_odeint_banded_jacobian
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_odeint.py", line 292, in test_odeint_banded_jacobian
    jacfn=jac)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/odeint.py", line 215, in odeint
    solver = ode(int_name, rhsfun, **options)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: scikits.odes.tests.test_odeint.test_odeint_errors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_odeint.py", line 403, in test_odeint_errors
    assert_raises(ZeroDivisionError, odeint, bad1, [0, 1], [1.0])
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/utils.py", line 1190, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 733, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/odeint.py", line 215, in odeint
    solver = ode(int_name, rhsfun, **options)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: Failure: ImportError (libsundials_cvode.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_on_funcs.py", line 16, in <module>
    from scikits.odes.sundials.cvode import StatusEnum
ImportError: libsundials_cvode.so.2: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_ida.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_on_funcs_ida.py", line 16, in <module>
    from scikits.odes.sundials.ida import StatusEnumIDA
ImportError: libsundials_ida.so.2: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_cvode.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_user_return_vals_cvode.py", line 5, in <module>
    from ..sundials.cvode import StatusEnum
ImportError: libsundials_cvode.so.2: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_ida.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/scikits/odes/tests/test_user_return_vals_ida.py", line 5, in <module>
    from ..sundials.ida import StatusEnumIDA
ImportError: libsundials_ida.so.2: cannot open shared object file: No such file or directory

----------------------------------------------------------------------
Ran 19 tests in 0.013s

FAILED (errors=16)
Out[2]: <nose.result.TextTestResult run=19 errors=16 failures=0>
```

May I know what is the reason for the errors? I have been trying out many different ways and tried to check online if anything similar but to no avail. Does anyone have any idea?

**Comment by sakimilo** [comment]
Hi, saw something related in this https://github.com/bmcage/odes/issues/56
I get nothing appears when `echo  LD_LIBRARY_PATH`
Hence, edited .bashrc with `export LD_LIBRARY_PATH=/usr/lib/sundials-2.7.0/lib/`
And, it works!

Is this how we should go about this issue?

**Comment by aragilar** [comment]
@sakimilo If that works for you then it's fine, don't change anything.
However, there's a few things which probably didn't help with the problem:
 1. Installing to `/usr/lib`: you should instead install to `/usr/local/lib` `/usr/lib` is for OS provided packages.
 2. You don't need to change any python things related to cmake
 3. You should attempt to install `scikits.odes` without specifying `SUNDIALS_INST`, as it's preferable for scikits.odes to automatically find sundials (which means scikits.odes should keep finding sundials). If this fails, then use `SUNDIALS_INST`.
