### ISSUE TITLE
Trouble finding sundials during the test stage of installing odes

### ISSUE THREAD

**Issue by dhalpern1** [bmcage/odes#79]
I installed odes, but the tests using the command
import scikits.odes as od; od.test()

fail.  I get the following output:

Running unit tests for scikits.odes
NumPy version 1.14.3
NumPy relaxed strides checking option: True
NumPy is installed in /usr/lib64/python2.7/site-packages/numpy
Python version 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
nose version 1.3.7
libsundials_ida.so.2: cannot open shared object file: No such file or directory
libsundials_cvode.so.2: cannot open shared object file: No such file or directory
EEException AttributeError: "'dae' object has no attribute '_integrator'" in <bound method dae.__del__ of <scikits.odes.dae.dae object at 0x7f4a48da2c50>> ignored
EException AttributeError: "'dae' object has no attribute '_integrator'" in <bound method dae.__del__ of <scikits.odes.dae.dae object at 0x7f4a488eb410>> ignored
E.EEEEEE.EE.EEEE
======================================================================
ERROR: Check the ddaspk solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 52, in test_ddaspk
    problem = problem_cls()
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 211, in __init__
    old_api=False,
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: Check the ida solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 71, in test_ida
    self._do_problem(problem, 'ida', old_api=False, **problem.ida_pars)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 27, in _do_problem
    ig = dae(integrator, res, jacfn=jac, old_api=old_api)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/dae.py", line 280, in __init__
    integrator = find_dae_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/dae.py", line 481, in find_dae_integrator
    raise ValueError('Integrator name %s does not exsist' % name)
ValueError: Integrator name ida does not exsist

======================================================================
ERROR: Check the ida solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 65, in test_ida_old_api
    self._do_problem(problem, 'ida', old_api=True, **problem.ida_pars)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 27, in _do_problem
    ig = dae(integrator, res, jacfn=jac, old_api=old_api)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/dae.py", line 280, in __init__
    integrator = find_dae_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/dae.py", line 481, in find_dae_integrator
    raise ValueError('Integrator name %s does not exsist' % name)
ValueError: Integrator name ida does not exsist

======================================================================
ERROR: Check the lsodi solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 58, in test_lsodi
    problem = problem_cls()
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 211, in __init__
    old_api=False,
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_get_info_is_exposed_on_ode (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_get_info_returns_dict (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_ode_exposes_num_rhs_evals (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_we_integrated_correctly (scikits.odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_ode_exposes_num_njtimes_evals (scikits.odes.tests.test_get_info.GetInfoTestSpils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 50, in setUp
    self.ode = ode('cvode', rhs, linsolver="spgmr", old_api=False)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_odeint (scikits.odes.tests.test_odeint.TestOdeint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_odeint.py", line 47, in test_odeint
    self._do_problem(problem)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_odeint.py", line 33, in _do_problem
    sol = odeint(problem.f, t, problem.z0, method=method)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/odeint.py", line 215, in odeint
    solver = ode(int_name, rhsfun, **options)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: scikits.odes.tests.test_odeint.test_odeint_banded_jacobian
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_odeint.py", line 292, in test_odeint_banded_jacobian
    jacfn=jac)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/odeint.py", line 215, in odeint
    solver = ode(int_name, rhsfun, **options)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: scikits.odes.tests.test_odeint.test_odeint_errors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_odeint.py", line 403, in test_odeint_errors
    assert_raises(ZeroDivisionError, odeint, bad1, [0, 1], [1.0])
  File "/usr/lib64/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 1191, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "/usr/lib64/python2.7/unittest/case.py", line 511, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/odeint.py", line 215, in odeint
    solver = ode(int_name, rhsfun, **options)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: Failure: ImportError (libsundials_cvode.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_on_funcs.py", line 16, in <module>
    from scikits.odes.sundials.cvode import StatusEnum
ImportError: libsundials_cvode.so.2: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_ida.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_on_funcs_ida.py", line 16, in <module>
    from scikits.odes.sundials.ida import StatusEnumIDA
ImportError: libsundials_ida.so.2: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_cvode.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_user_return_vals_cvode.py", line 5, in <module>
    from ..sundials.cvode import StatusEnum
ImportError: libsundials_cvode.so.2: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_ida.so.2: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/dhalpern/.local/lib/python2.7/site-packages/scikits/odes/tests/test_user_return_vals_ida.py", line 5, in <module>
    from ..sundials.ida import StatusEnumIDA
ImportError: libsundials_ida.so.2: cannot open shared object file: No such file or directory

----------------------------------------------------------------------
Ran 19 tests in 0.009s

FAILED (errors=16)
<nose.result.TextTestResult run=19 errors=16 failures=0>
>>> 

FYI, I have sundials installed in /usr/local/sundials27

I tried to modify scikits/odes/sundials/setup.py but this didn't work.

Any suggestions would be greatly appreciated.

**Comment by bmcage** [comment]
Clearly the files are not found. Normally you install in /usr/local, so files are in /usr/local/include and /usr/local/lib/, ...
So you installed in non standard way, so you need to set $SUNDIALS_INST
See https://scikits-odes.readthedocs.io/en/latest/installation.html

Perhaps easier to not set install path when you install sundials, so not 

    cmake -DLAPACK_ENABLE=ON -DCMAKE_INSTALL_PREFIX=<install_path> ../sundials-2.7.0/

but 

    cmake -DLAPACK_ENABLE=ON  ../sundials-2.7.0/

**Comment by dhalpern1** [comment]
Thanks,

BUT I should have add that I  looked at the the installation link and set $SUNDIALS_INST as mentioned before posting my message.

I am not sure I understand what you mean by not setting the install path since Sundials has to be installed somewhere.

**Comment by bmcage** [comment]
it goes to the default /usr/local if you give nothing
