### ISSUE TITLE
Unable to install scikits.odes using conda

### ISSUE THREAD

**Issue by vahidmech** [bmcage/odes#86]
I am going to install scikit.odes on Ubuntu 
I do the following steps from an earlier [post](https://github.com/bmcage/odes/issues/56) 

`conda create -n odes numpy cython`
`conda install -n odes -c conda-forge sundials=2.7.0`
`export SUNDIALS_INST="${HOME}/anaconda3/pkgs/sundials-2.7.0-blas_openblash0edd121_6"`

`source activate odes`
`pip install scikits.odes`

but I get an error [log.txt](https://github.com/bmcage/odes/files/2515947/log.txt)

**Comment by bmcage** [comment]
No experience with conda myself. 
It would be better if you try install of master with sundials 3.1.1 instead. I did not find the time yet for a release, but master is release ready. So after sundials 3.1.1 install, do https://scikits-odes.readthedocs.io/en/latest/installation.html#installation-of-odes-from-git-checkout

**Comment by vahidmech** [comment]
Thanks for your reply!
I installed without using conda, however, I get an error when I try to test.

 >>> import scikits.odes as od
>>> od.test()
Running unit tests for scikits.odes
NumPy version 1.15.3
NumPy relaxed strides checking option: True
NumPy is installed in /home/vahid/.local/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
nose version 1.3.7
Elibsundials_cvode.so.3: cannot open shared object file: No such file or directory
.EEEEEEEEEE
======================================================================
ERROR: Failure: ImportError (libsundials_nvecserial.so.3: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_dae.py", line 15, in <module>
    from scikits.odes.sundials.common_defs import DTYPE
ImportError: libsundials_nvecserial.so.3: cannot open shared object file: No such file or directory

======================================================================
ERROR: test_get_info_is_exposed_on_ode (odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_get_info_returns_dict (odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_ode_exposes_num_rhs_evals (odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_we_integrated_correctly (odes.tests.test_get_info.GetInfoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 23, in setUp
    self.ode = ode('cvode', rhs, old_api=False)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: test_ode_exposes_num_njtimes_evals (odes.tests.test_get_info.GetInfoTestSpils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_get_info.py", line 50, in setUp
    self.ode = ode('cvode', rhs, linsolver="spgmr", old_api=False)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 273, in __init__
    integrator = find_ode_integrator(integrator_name)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/ode.py", line 486, in find_ode_integrator
    raise ValueError('Integrator name %s does not exist' % name)
ValueError: Integrator name cvode does not exist

======================================================================
ERROR: Failure: ImportError (libsundials_nvecserial.so.3: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_odeint.py", line 23, in <module>
    from scikits.odes.sundials.common_defs import DTYPE
ImportError: libsundials_nvecserial.so.3: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_cvode.so.3: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_on_funcs.py", line 16, in <module>
    from scikits.odes.sundials.cvode import StatusEnum
ImportError: libsundials_cvode.so.3: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_ida.so.3: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_on_funcs_ida.py", line 16, in <module>
    from scikits.odes.sundials.ida import StatusEnumIDA
ImportError: libsundials_ida.so.3: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_cvode.so.3: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_user_return_vals_cvode.py", line 5, in <module>
    from ..sundials.cvode import StatusEnum
ImportError: libsundials_cvode.so.3: cannot open shared object file: No such file or directory

======================================================================
ERROR: Failure: ImportError (libsundials_ida.so.3: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vahid/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vahid/.local/lib/python2.7/site-packages/scikits/odes/tests/test_user_return_vals_ida.py", line 5, in <module>
    from ..sundials.ida import StatusEnumIDA
ImportError: libsundials_ida.so.3: cannot open shared object file: No such file or directory

----------------------------------------------------------------------
Ran 12 tests in 0.006s

FAILED (errors=11)
<nose.result.TextTestResult run=12 errors=11 failures=0>

**Comment by ingegno** [comment]
Error is in finding the sundials lib, eg: 

    libsundials_cvode.so.3: cannot open shared object file: No such file or directory

So, did you install sundials 3.1.1 ? 
After installation of sundials, look up the install directory. Pass it correctly to the pip installer:
https://scikits-odes.readthedocs.io/en/latest/installation.html#linking-errors 

See also: https://github.com/bmcage/odes/blob/master/docs/installation.rst

**Comment by vahidmech** [comment]
Thanks for your reply!

Yes, I have installed sundials 3.1.1 and I was passing the installation directory using `$SUNDIALS_INST` already.

I added `export LD_LIBRARY_PATH=$SUNDIALS_INST/lib:$LD_LIBRARY_PATH` which is only written here (and not in the other site): https://github.com/bmcage/odes/blob/master/docs/installation.rst.
Now, I get the following results after running the tests. It seems there is no problem with the packages but there are some massage like
"[CVDLS ERROR]  cvDlsSetup
  The Jacobian routine failed in an unrecoverable manner."
Does it mean there is still a problem in installing the packages? For me, it is more like that there is a problem in calculations. 

>>> import scikits.odes as od
>>> od.test()
Running unit tests for scikits.odes
NumPy version 1.15.3
NumPy relaxed strides checking option: True
NumPy is installed in /home/vahid/.local/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
nose version 1.3.7
../home/vahid/.local/lib/python2.7/site-packages/scikits/odes/dae.py:389: DeprecationWarning: Old api is deprecated, move to new api
  return self._integrator.init_step(t0, y0, yp0, y_ic0_retn, yp_ic0_retn)
.....ode.get_info() =
 {'NumRhsEvals': 27, 'CurrentOrder': 2, 'NumErrTestFails': 1, 'ActualInitStep': 0.0005000002493687262, 'CurrentStep': 11.121864790716213, 'LastOrder': 2, 'NumSteps': 19, 'NumLinSolvSetups': 16, 'LastStep': 5.632767015984214}
.True solution:
 [  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
Integrated:
 [  1.           4.00000181   9.00000189  16.00000196  25.00000201
  36.00000205  49.00000213  64.00000218  81.00000222 100.00000225]
Difference:
 [0.00000000e+00 1.80709183e-06 1.88536923e-06 1.95964127e-06
 2.00559588e-06 2.05370031e-06 2.12527937e-06 2.18137134e-06
 2.22197630e-06 2.24709419e-06]
Relative:
 [0.00000000e+00 4.51772957e-07 2.09485470e-07 1.22477579e-07
 8.02238353e-08 5.70472309e-08 4.33730483e-08 3.40839272e-08
 2.74318062e-08 2.24709419e-08]
.ode.get_info() =
 {'NumPrecEvals': 0, 'NumRhsEvals': 29, 'LastOrder': 2, 'NumSteps': 19, 'NumLinSolvSetups': 0, 'CurrentStep': 11.121864790716213, 'CurrentOrder': 2, 'NumRhsEvalsJtimesFD': 20, 'ActualInitStep': 0.0005000002493687262, 'NumJtimesEvals': 20, 'NumLinIters': 20, 'NumErrTestFails': 1, 'LastStep': 5.632767015984214, 'NumPrecSolves': 0}
..............................
[CVDLS ERROR]  cvDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the setup routine failed in an unrecoverable manner.

.
[CVDLS ERROR]  cvDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the setup routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  At t = 0 and h = 2.6974e-09, the corrector convergence test failed repeatedly or with |h| = hmin.

.
[CVODE ERROR]  CVode
  At t = 0 and h = 1.90735e-09, the corrector convergence test failed repeatedly or with |h| = hmin.

.
[CVSPILS ERROR]  cvSpilsSolve
  The Jacobian x vector routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the solve routine failed in an unrecoverable manner.

.
[CVSPILS ERROR]  cvSpilsSolve
  The Jacobian x vector routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the solve routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  At t = 0.0314249, mxstep steps taken before reaching tout.

.
[CVODE ERROR]  CVode
  At t = 0.0222206, mxstep steps taken before reaching tout.

.......
[CVODE ERROR]  CVode
  At t = 0, the right-hand side routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  At t = 0.458122, the right-hand side routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  The right-hand side routine failed at the first call.

.
[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.70033e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.70033e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.25083e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.25083e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 2.65677e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 2.65677e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.66048e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.66048e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.1512e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.1512e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  The above warning has been issued mxhnil times and will not be issued again for this problem.


[CVODE ERROR]  CVode
  At t = 0.5, mxstep steps taken before reaching tout.

..
[CVODE ERROR]  cvRcheck1
  At t = 0, the rootfinding routine failed in an unrecoverable manner.

.
[CVODE ERROR]  cvRcheck3
  At t = 0.458122, the rootfinding routine failed in an unrecoverable manner.

.
[CVODES WARNING]  CVode
  At the end of the first step, there are still some root functions identically 0. This warning will not be issued again.

...
[IDADLS ERROR]  idaDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[IDA ERROR]  IDASolve
  At t = 0, the linear solver setup failed unrecoverably.

.
[IDADLS ERROR]  idaDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[IDA ERROR]  IDASolve
  At t = 0, the linear solver setup failed unrecoverably.

.
[IDA ERROR]  IDASolve
  At t = 0 and h = 9.53674e-10, the corrector convergence failed repeatedly or with |h| = hmin.

.
[IDA ERROR]  IDASolve
  At t = 0 and h = 9.53674e-10, the corrector convergence failed repeatedly or with |h| = hmin.

.....
[IDA ERROR]  IDASolve
  At t = 0, the residual function failed unrecoverably.

.
[IDA ERROR]  IDASolve
  At t = 0.287979, the residual function failed unrecoverably.

.
[IDA ERROR]  IDASolve
  At t = 0, repeated recoverable residual errors.

.
[IDA ERROR]  IDASolve
  At t = 0.5, , mxstep steps taken before reaching tout.

..
[IDA ERROR]  IDARcheck1
  At t = 0, , the rootfinding routine failed in an unrecoverable manner.

.
[IDA ERROR]  IDARcheck3
  At t = 0.287979, , the rootfinding routine failed in an unrecoverable manner.

.
[IDA WARNING]  IDASolve
  At the end of the first step, there are still some root functions identically 0. This warning will not be issued again.

...
----------------------------------------------------------------------
Ran 81 tests in 0.709s

OK
<nose.result.TextTestResult run=81 errors=0 failures=0>

**Comment by bmcage** [comment]
We test in the test suite if the solver fails when we expect it to fail. So those errors are expected and good, as it says in the end. 81 tests run, all OK.

**Comment by utsekaj42** [comment]
Just thought I would add what actually solves the problem as stated in the title of this issue, maybe based on what I've found a new issue should be opened, @bmcage? I'm not sure if the issue is due to scikits.odes, conda or other.

The following works for me on fedora and the continuum:anaconda docker image
```
conda create -n test -c conda-forge blas gcc_linux-64 fortran-compiler cmake make nose cython numpy 
conda activate test
wget  https://computing.llnl.gov/projects/sundials/download/sundials-3.1.1.tar.gz
tar xvf sundials-3.1.1.tar.gz
mkdir sundials_build
cd sundials_build
cmake \
-DLAPACK_ENABLE=ON \
 -DSUNDIALS_INDEX_TYPE=int32_t \
-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ../sundials-3.1.1/  
make install
SUNDIALS_INST=$CONDA_PREFIX NPY_DISTUTILS_APPEND_FLAGS=1 pip install scikits.odes 
```

I'm not sure why NPY_DISTUTILS_APPEND_FLAGS=1 is necessary, though the error message when not using it suggests that his will be irrelevant in the future when this becomes the default.

Additionally, it seems odd to me that `SUNDIALS_INST=$CONDA_PREFIX` is necessary as in the conda environment `$CONDA_PREFIX` is basically `/usr` and most other software, sundials included, doesn't need to explicitly know about this to find dependencies. Is there some environment variable these are looking at that scikits.odes is not?

**Comment by resperic** [comment]
I tried installing it as described by utsekaj42 above, on my Ubuntu 18.04 system, but ended up with the error message:
**Failed to build scikits.odes
ERROR: Could not build wheels for scikits.odes which use PEP 517 and cannot be installed directly**

**Comment by bmcage** [comment]
I assume you want to use pip? Then you are installing latest version, which is not based on sundials 3.1.1 as given by utsekaj42 but already sundials 5.0.0
I see I forgot to rebuild readthedocs, I did that now, current install instructions: https://scikits-odes.readthedocs.io/en/latest/installation.html

**Comment by userrand** [comment]
> Error is in finding the sundials lib, eg:
> 
> ```
> libsundials_cvode.so.3: cannot open shared object file: No such file or directory
> ```
> 
> So, did you install sundials 3.1.1 ? After installation of sundials, look up the install directory. Pass it correctly to the pip installer: https://scikits-odes.readthedocs.io/en/latest/installation.html#linking-errors
> 
> See also: https://github.com/bmcage/odes/blob/master/docs/installation.rst

how do you pass the installation directory to the pip installer ? Do I use `export SUNDIALS_INST=/path/to/sundials` ?
