### ISSUE TITLE
problem with pip install, can't import common

### ISSUE THREAD

**Issue by martinjrobins** [bmcage/odes#89]
I'm trying to install odes on an ubuntu 18.04 system. I've installed the dependencies and sundials as per the instructions here: https://scikits-odes.readthedocs.io/en/latest/installation.html#requirements-before-install

when I try to install odes with the command:

```bash
SUNDIALS_INST=/home/mrobins/sundials-3.1.1/install pip install scikits.odes
```
It falls over with the error shown below. 

```
Collecting scikits.odes
  Using cached https://files.pythonhosted.org/packages/91/65/ab7ebd1a9a921f96bfb3d4e38db3c203e0f7e0781d73e35139277ea04baa/scikits.odes-2.4.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/mrobins/tmp/test/bin/python3 /home/mrobins/tmp/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp4httixax:
  Traceback (most recent call last):
    File "/home/mrobins/tmp/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/mrobins/tmp/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/mrobins/tmp/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-163crzl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-163crzl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/tmp/pip-build-env-163crzl0/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 15, in <module>
      from common import *
  ModuleNotFoundError: No module named 'common'

  ----------------------------------------
Command "/home/mrobins/tmp/test/bin/python3 /home/mrobins/tmp/test/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp4httixax" failed with error code 1 in /tmp/pip-install-nja1jf80/scikits.odes
```

It looks like it can't see the `common.py` in the root directory of your repo, but I can't see why not.

**Comment by martinjrobins** [comment]
it is pip version 19.0.1 from python 3.6

**Comment by aragilar** [comment]
Pip 19 broke a bunch of things, try pip 18, that should work.

**Comment by martinjrobins** [comment]
Yes, going back to pip 18 worked perfectly. Thanks @aragilar
