### ISSUE TITLE
Tests Fail

### ISSUE THREAD

**Issue by idontgetoutmuch** [bmcage/odes#95]
I appear to have installed `scikit-odes` successfully

```
bash-3.2$ CC=gcc-9 pip3 install scikits.odes
CC=gcc-9 pip3 install scikits.odes
Collecting scikits.odes
  Using cached https://files.pythonhosted.org/packages/91/65/ab7ebd1a9a921f96bfb3d4e38db3c203e0f7e0781d73e35139277ea04baa/scikits.odes-2.4.0.tar.gz
  Installing build dependencies ... done
Requirement already satisfied: scipy in /usr/local/lib/python3.7/site-packages (from scikits.odes) (1.3.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/site-packages (from scipy->scikits.odes) (1.16.0)
Building wheels for collected packages: scikits.odes
  Running setup.py bdist_wheel for scikits.odes ... done
  Stored in directory: /Users/dominic.steinitz/Library/Caches/pip/wheels/5f/6e/6e/e0623cfb3bc8e90514e6b4c66e9587ecd83922304912fc9bed
Successfully built scikits.odes
Installing collected packages: scikits.odes
Successfully installed scikits.odes-2.4.0
bash-3.2$ python3
python3
Python 3.7.0 (default, Oct  2 2018, 09:20:07) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
import pkg_resources
>>> pkg_resources.get_distribution("scikits.odes").version
pkg_resources.get_distribution("scikits.odes").version
'2.4.0'
>>> quit()
quit()
```

But the tests fail

```
bash-3.2$ python3
python3
Python 3.7.0 (default, Oct  2 2018, 09:20:07) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scikits.odes as od; od.test()
import scikits.odes as od; od.test()
Running unit tests for scikits.odes
NumPy version 1.16.0
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python3.7/site-packages/numpy
Python version 3.7.0 (default, Oct  2 2018, 09:20:07) [Clang 10.0.0 (clang-1000.11.45.2)]
nose version 1.3.7
/usr/local/lib/python3.7/site-packages/nose/suite.py:106: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(tests, collections.Callable) and not is_suite:
../usr/local/lib/python3.7/site-packages/scikits/odes/dae.py:389: DeprecationWarning: Old api is deprecated, move to new api
  return self._integrator.init_step(t0, y0, yp0, y_ic0_retn, yp_ic0_retn)
.....ode.get_info() =
 {'NumSteps': 19, 'NumRhsEvals': 27, 'NumLinSolvSetups': 16, 'NumErrTestFails': 1, 'LastOrder': 2, 'CurrentOrder': 2, 'ActualInitStep': 0.0005000002493687262, 'LastStep': 5.632767015984214, 'CurrentStep': 11.121864790716213}
.True solution:
 [  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
Integrated:
 [  1.           4.00000181   9.00000189  16.00000196  25.00000201
  36.00000205  49.00000213  64.00000218  81.00000222 100.00000225]
Difference:
 [0.00000000e+00 1.80709183e-06 1.88536923e-06 1.95964127e-06
 2.00559588e-06 2.05370031e-06 2.12527937e-06 2.18137134e-06
 2.22197630e-06 2.24709419e-06]
Relative:
 [0.00000000e+00 4.51772957e-07 2.09485470e-07 1.22477579e-07
 8.02238353e-08 5.70472309e-08 4.33730483e-08 3.40839272e-08
 2.74318062e-08 2.24709419e-08]
.ode.get_info() =
 {'NumSteps': 19, 'NumRhsEvals': 29, 'NumLinSolvSetups': 0, 'NumErrTestFails': 1, 'LastOrder': 2, 'CurrentOrder': 2, 'ActualInitStep': 0.0005000002493687262, 'LastStep': 5.632767015984214, 'CurrentStep': 11.121864790716213, 'NumPrecEvals': 0, 'NumPrecSolves': 0, 'NumJtimesEvals': 20, 'NumLinIters': 20, 'NumRhsEvalsJtimesFD': 20}
...E..........................
[CVDLS ERROR]  cvDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the setup routine failed in an unrecoverable manner.

.
[CVDLS ERROR]  cvDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the setup routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  At t = 0 and h = 2.6974e-09, the corrector convergence test failed repeatedly or with |h| = hmin.

.
[CVODE ERROR]  CVode
  At t = 0 and h = 1.90735e-09, the corrector convergence test failed repeatedly or with |h| = hmin.

.
[CVSPILS ERROR]  cvSpilsSolve
  The Jacobian x vector routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the solve routine failed in an unrecoverable manner.

.
[CVSPILS ERROR]  cvSpilsSolve
  The Jacobian x vector routine failed in an unrecoverable manner.


[CVODE ERROR]  CVode
  At t = 0, the solve routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  At t = 0.0314249, mxstep steps taken before reaching tout.

.
[CVODE ERROR]  CVode
  At t = 0.0222206, mxstep steps taken before reaching tout.

.......
[CVODE ERROR]  CVode
  At t = 0, the right-hand side routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  At t = 0.458122, the right-hand side routine failed in an unrecoverable manner.

.
[CVODE ERROR]  CVode
  The right-hand side routine failed at the first call.

.
[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.70033e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.70033e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.25083e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.25083e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 2.65677e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 2.65677e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.66048e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 1.66048e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.1512e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  Internal t = 0.5 and h = 4.1512e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODE WARNING]  CVode
  The above warning has been issued mxhnil times and will not be issued again for this problem.


[CVODE ERROR]  CVode
  At t = 0.5, mxstep steps taken before reaching tout.

..
[CVODE ERROR]  cvRcheck1
  At t = 0, the rootfinding routine failed in an unrecoverable manner.

.
[CVODE ERROR]  cvRcheck3
  At t = 0.458122, the rootfinding routine failed in an unrecoverable manner.

.
[CVODES WARNING]  CVode
  At the end of the first step, there are still some root functions identically 0. This warning will not be issued again.

...
[IDADLS ERROR]  idaDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[IDA ERROR]  IDASolve
  At t = 0, the linear solver setup failed unrecoverably.

.
[IDADLS ERROR]  idaDlsSetup
  The Jacobian routine failed in an unrecoverable manner.


[IDA ERROR]  IDASolve
  At t = 0, the linear solver setup failed unrecoverably.

.
[IDA ERROR]  IDASolve
  At t = 0 and h = 9.53674e-10, the corrector convergence failed repeatedly or with |h| = hmin.

.
[IDA ERROR]  IDASolve
  At t = 0 and h = 9.53674e-10, the corrector convergence failed repeatedly or with |h| = hmin.

.....
[IDA ERROR]  IDASolve
  At t = 0, the residual function failed unrecoverably.

.
[IDA ERROR]  IDASolve
  At t = 0.287979, the residual function failed unrecoverably.

.
[IDA ERROR]  IDASolve
  At t = 0, repeated recoverable residual errors.

.
[IDA ERROR]  IDASolve
  At t = 0.5, , mxstep steps taken before reaching tout.

..
[IDA ERROR]  IDARcheck1
  At t = 0, , the rootfinding routine failed in an unrecoverable manner.

.
[IDA ERROR]  IDARcheck3
  At t = 0.287979, , the rootfinding routine failed in an unrecoverable manner.

.
[IDA WARNING]  IDASolve
  At the end of the first step, there are still some root functions identically 0. This warning will not be issued again.

...
======================================================================
ERROR: odes.tests.test_odeint.test_odeint_banded_jacobian
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.7/site-packages/scikits/odes/tests/test_odeint.py", line 330, in test_odeint_banded_jacobian
    linsolver='lapackdense')
  File "/usr/local/lib/python3.7/site-packages/scikits/odes/odeint.py", line 216, in odeint
    return solver.solve(t, y0)
  File "/usr/local/lib/python3.7/site-packages/scikits/odes/ode.py", line 333, in solve
    return self._integrator.solve(tspan, y0)
  File "scikits/odes/sundials/cvode.pyx", line 1724, in scikits.odes.sundials.cvode.CVODE.solve
  File "scikits/odes/sundials/cvode.pyx", line 1762, in scikits.odes.sundials.cvode.CVODE._solve
  File "scikits/odes/sundials/cvode.pyx", line 1577, in scikits.odes.sundials.cvode.CVODE._init_step
ValueError: LinSolver: Unknown solver type: lapackdense

----------------------------------------------------------------------
Ran 81 tests in 0.519s

FAILED (errors=1)
<nose.result.TextTestResult run=81 errors=1 failures=0>
>>> quit()
quit()
```

**Comment by idontgetoutmuch** [comment]
As another data point this

```
import numpy as np
from scikits.odes.odeint import odeint

tout = np.linspace(0, 1)
initial_values = np.array([1])

def right_hand_side(t, y, ydot):
    ydot[0] = y[0]

output = odeint(right_hand_side, tout, initial_values)
print(output.values.y)
```

gives

```
[[1.        ]
 [1.02061945]
 [1.04166278]
 [1.06313979]
 [1.08505944]
 [1.10743106]
 [1.13026421]
 [1.15356813]
 [1.17735274]
 [1.20162809]
 [1.22640354]
 [1.25168979]
 [1.27749718]
 [1.30383671]
 [1.33071923]
 [1.358156  ]
 [1.38615868]
 [1.41473877]
 [1.44390794]
 [1.4736788 ]
 [1.50406327]
 [1.5350741 ]
 [1.56672433]
 [1.59902692]
 [1.63199553]
 [1.66564382]
 [1.69998582]
 [1.73503587]
 [1.77080857]
 [1.80731883]
 [1.84458187]
 [1.88261319]
 [1.92142879]
 [1.96104473]
 [2.00147747]
 [2.04274371]
 [2.08486113]
 [2.12784696]
 [2.171719  ]
 [2.21649536]
 [2.26219525]
 [2.30883742]
 [2.35644117]
 [2.40502615]
 [2.45461309]
 [2.5052225 ]
 [2.55687528]
 [2.6095928 ]
 [2.66339741]
 [2.7183115 ]]
```

as expected.

**Comment by aragilar** [comment]
Apparently your sundials install didn't link to lapack (so the solver can't use `lapackdense`). We probably want to add a skip if sundials isn't linked to lapack, but otherwise everything is fine.

**Comment by idontgetoutmuch** [comment]
Bother - I can see that now in my notes in #96 - I did originally have `-DLAPACK_ENABLE=ON` but as I tried to coax SUNDIALS to build but I must have missed it off on the build that actually succeeded. I guess I can just rebuild with the missing option. Thanks for the pointer. I'll give it a go and then hopefully can close the ticket.

**Comment by idontgetoutmuch** [comment]
Rebuilding with `-DLAPACK_ENABLE=ON` didn't seem to improve the situation. Maybe the sundials build system isn't picking up my lapack. I'll have to investigate further.

**Comment by idontgetoutmuch** [comment]
It seems one needs `cmake -DLAPACK_ENABLE=ON -DSUNDIALS_INDEX_TYPE=int32_t` - I missed the warning that told me this.

But now I am in a worse position than before

```
bash-3.2$ python3
python3
Python 3.7.0 (default, Oct  2 2018, 09:20:07) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scikits.odes as od; od.test()
import scikits.odes as od; od.test()
Running unit tests for scikits.odes
NumPy version 1.16.0
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python3.7/site-packages/numpy
Python version 3.7.0 (default, Oct  2 2018, 09:20:07) [Clang 10.0.0 (clang-1000.11.45.2)]
nose version 1.3.7
/usr/local/lib/python3.7/site-packages/nose/suite.py:106: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(tests, collections.Callable) and not is_suite:
Segmentation fault: 11
```

**Comment by idontgetoutmuch** [comment]
After rebuilding everything I can think of, I still get a segmentation fault. So something must be caching something. Any tips gratefully received.

**Comment by aragilar** [comment]
You want `pip install --no-binary` (or you can go into your pip wheel cache and remove the wheel - see https://pip.pypa.io/en/stable/reference/pip_install/#caching). Segfault is mismatching APIs for ints (most likely).

**Comment by idontgetoutmuch** [comment]
Thanks very much :) I am now back to the lapack issue. I am going to close this ticket and open another to all the noise.
